[project]
name = "gwt-test-framework"
version = "0.1.0"
description = "A Python framework for declaring Given-When-Then tests"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pre-commit>=4.0.1",
]

[tool.ruff]
target-version = "py312"
line-length = 120
